# Generated by Django 6.0.4 on 2026-04-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FatLossLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('goal_completion', models.BooleanField(default=False)),
                ('weight', models.FloatField(help_text='Weight in kg')),
                ('waist_size', models.FloatField(help_text='Waist size in inches')),
                ('thigh_size', models.FloatField(help_text='Thigh size in inches')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
